Importing the Dependencies

In [93]:
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [94]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

Data Collection and Analysis

pima diabetes dataset

In [95]:
#loading the biabetes dataset to a pandas DataFrame
diabetes_Dataset = pd.read_csv("/content/diabetes.csv")

In [96]:
diabetes_Dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [97]:
diabetes_Dataset.shape

(768, 9)

In [98]:
#statistical measures of data
diabetes_Dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [99]:
diabetes_Dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

0 --> Non diabetic

1 --> biabetic

In [100]:
diabetes_Dataset.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [101]:
#seprating data and the labels
x = diabetes_Dataset.drop(columns = 'Outcome', axis = 1)
y = diabetes_Dataset['Outcome']

In [102]:
print(x)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [103]:
print(y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Data Standerdization

In [104]:
scalar = StandardScaler()

In [105]:
scalar.fit(x)

StandardScaler()

In [106]:
standardized_data = scalar.transform(x)

In [107]:
print(standardized_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [108]:
x = standardized_data
y = diabetes_Dataset['Outcome']

In [109]:
print(x)
print(y)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

# **Train Test Split**

In [110]:
X_train, X_test, Y_train, Y_test = train_test_split(x , y , test_size = 0.2 , stratify= y , random_state= 2)

In [111]:
print(x.shape ,X_train.shape, X_test.shape)

(768, 8) (614, 8) (154, 8)

**Comparing the performance of the model**

In [112]:
# list of models
models = [LogisticRegression(max_iter=1000), svm.SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [113]:
def compair_model_train_test():
  for model in models:
    model.fit(X_train, Y_train)
    test_data_prediction = model.predict(X_test)
    accuracy = accuracy_score(Y_test, test_data_prediction)
    print('Accuracy score of the ', model, ' = ', accuracy)

In [114]:
compair_model_train_test()

Accuracy score of the  LogisticRegression(max_iter=1000)  =  0.7597402597402597
Accuracy score of the  SVC(kernel='linear')  =  0.7727272727272727
Accuracy score of the  KNeighborsClassifier()  =  0.7207792207792207
Accuracy score of the  RandomForestClassifier()  =  0.7337662337662337

#  **Cross Validation**

Logisctic Resgression

In [116]:
cv_score = cross_val_score(LogisticRegression(max_iter=1000), x, y, cv=5)

print(cv_score)

mean_accuracy = sum(cv_score)/len(cv_score)

mean_accuracy = mean_accuracy*100

mean_accuracy = round(mean_accuracy, 2)

print(mean_accuracy)

[0.77272727 0.74675325 0.75324675 0.81699346 0.76470588]
77.09

Support Vector Classifier

In [118]:
cv_score_svm = cross_val_score(svm.SVC(kernel='linear'), x, y, cv=5)

print(cv_score_svm)

mean_accuracy_svm = sum(cv_score_svm)/len(cv_score_svm)

mean_accuracy_svm = mean_accuracy_svm*100

mean_accuracy_svm = round(mean_accuracy_svm, 2)

print(mean_accuracy_svm)

[0.76623377 0.75974026 0.75974026 0.81699346 0.76470588]
77.35

Creating the function  to compair the models

In [119]:
# list of models
models = [LogisticRegression(max_iter=1000), svm.SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [120]:
def compair_model_cross_validation():

  for model in models:

    cv_score = cross_val_score(model, x, y, cv=5)

    mean_accuracy = sum(cv_score)/len(cv_score)

    mean_accuracy = mean_accuracy*100

    mean_accuracy = round(mean_accuracy, 2)

    print('Cross Validation accuracies for the' ,model ,"=" , cv_score)
    print("Accuracy % of the " , model , mean_accuracy)
    print('------------------------------------------------------')

In [121]:
compair_model_cross_validation()

Cross Validation accuracies for the LogisticRegression(max_iter=1000) = [0.77272727 0.74675325 0.75324675 0.81699346 0.76470588]
Accuracy % of the  LogisticRegression(max_iter=1000) 77.09
------------------------------------------------------
Cross Validation accuracies for the SVC(kernel='linear') = [0.76623377 0.75974026 0.75974026 0.81699346 0.76470588]
Accuracy % of the  SVC(kernel='linear') 77.35
------------------------------------------------------
Cross Validation accuracies for the KNeighborsClassifier() = [0.72077922 0.73376623 0.71428571 0.77124183 0.7254902 ]
Accuracy % of the  KNeighborsClassifier() 73.31
------------------------------------------------------
Cross Validation accuracies for the RandomForestClassifier() = [0.75974026 0.72077922 0.75974026 0.83660131 0.74509804]
Accuracy % of the  RandomForestClassifier() 76.44
------------------------------------------------------